version: '3'
services:
  get1:
    container_name: get1
    image: stephan/myapp
    build:
      context: .
    ports:
      - "3000"
    volumes:
      - .:/app
  get2:
    container_name: get2
    image: stephan/myapp
    build:
      context: .
    ports:
      - "3000"
    volumes:
      - .:/app
  post1:
    container_name: post1
    image: stephan/myapp
    build:
      context: .
    ports:
      - "3000"
    volumes:
      - .:/app
  post2:
    container_name: post2
    image: stephan/myapp
    build:
      context: .
    ports:
      - "3000"
    volumes:
      - .:/app
  nginx:
      restart: always
      build:
        context: ./nginx
      ports:
        - "80:80"

